name: cve-monitor

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  cve-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    environment: CI
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: run scraper
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python3 main.py
      - name: save changes
        run: |
          git config --global user.email "cve-monitor@users.noreply.github.com"
          git config --global user.name "CVE-Bot"
          git add .
          git commit --all --message "Updated by CVE-Bot 🤖" || echo "no changes to commit"
          git push
      - name: 确保.nojekyll文件存在
        run: |
          touch docs/.nojekyll
          git add docs/.nojekyll
          git commit -m "Add or update .nojekyll file" || echo ".nojekyll already exists"
      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          allow_empty_commit: false
          commit_message: Updated by CVE-Bot 🤖
          keep_files: false